language: ruby
rvm:
  - 2.1.6
before_script:
  - gem install bundler
  - "cd spec/dummy"
  - "RAILS_ENV=test bundle exec rake db:migrate --trace"
  - "cd ../.."
  - "appraisal install"
script: "appraisal rspec"
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile