language: ruby
rvm:
  - 2.1.6
before_script:
  - gem install bundler
  - "cd spec/dummy"
  - "RAILS_ENV=test bundle exec rake db:migrate --trace"
  - "cd ../.."
script: "bundle exec rspec"
gemfile:
  - gemfiles/ruby2.2_rails3.2.gemfile
  - gemfiles/ruby2.2_rails4.0.gemfile
  - gemfiles/ruby2.2_rails4.1.gemfile
  - gemfiles/ruby2.2_rails4.2.gemfile
  - gemfiles/ruby2.1_rails3.2.gemfile
  - gemfiles/ruby2.1_rails4.0.gemfile
  - gemfiles/ruby2.1_rails4.1.gemfile
  - gemfiles/ruby2.1_rails4.2.gemfile
  - gemfiles/ruby2.0_rails3.2.gemfile
  - gemfiles/ruby2.0_rails4.0.gemfile
  - gemfiles/ruby2.0_rails4.1.gemfile
  - gemfiles/ruby2.0_rails4.2.gemfile